### ISSUE TITLE
Some of the colors in the "Most popular edition..." map are too similar

### ISSUE THREAD

**Issue by MarcAbonce** [a455bcd9/wikilangtrends#1]
Hi, I just found your map in https://commons.wikimedia.org/wiki/File:Most_popular_edition_of_Wikipedia_by_country_Jan_2021.svg and in my screen the colors for French and Arabic look very similar to each other which makes the map confusing, specially around the Maghreb where both languages overlap. The same is true to a much lesser extent with English and Russian. I didn't realise at first that Estonia actually had the English color until I zoomed in.

Other than that I loved the map, though, very interesting.

**Comment by a455bcd9** [comment]
Hi @MarcAbonce 
Sorry for the late reply. You're right; the colors for French and Arabic are too close to each other; I'm color blind, and it's also an issue for me...

I used pygal to generate the SVG map. Apparently, it's possible to define the colors with pygal ( https://stackoverflow.com/questions/47945118/how-to-set-specific-color-for-each-category-when-using-pygal-maps-world-drawin ). However, pygal generates incorrect SVG that is not displayed on Wikimedia and has to be changed manually. So I don't want to use it anymore...

I tried another library (geopandas), but it only generates PNG, and it's not easy either to choose custom colors: https://github.com/geopandas/geopandas/issues/1269

So I manually edited the SVG image on Wikimedia. I couldn't find a standard color scheme for languages. So I invented mine... You can see the result here: https://commons.wikimedia.org/wiki/File:Most_popular_edition_of_Wikipedia_by_country_Jan_2021.svg

What do you think?

By the way, I wrote an article about this map and the different trends regarding the usage of languages on Wikipedia, I hope you'll find it interesting as well, feel free to comment! https://adssx.substack.com/p/the-rise-of-the-rest :)

**Comment by MarcAbonce** [comment]
Great! Thank you!
